### ISSUE TITLE
Picklist Values

### ISSUE THREAD

**Issue by ptdesign** [salaros/vtwsclib-php#12]
Ability to retrieve in Array label instead values from picklistValues

**Comment by salaros** [comment]
Hm.. if I'm getting you correctly you want to retrieve an entity/list of entities with picklist-type fields containing label representation instead of raw values, right?

You have two options:
1. Use `$client->modules->getOne('YouModuleName')` to retrieve the list of picklist fields and their labels, so then you can use that for replacing the raw values with labels
2. [Define your own version](https://github.com/salaros/vtwsclib-php/wiki#more-stuff-extensibility) of retrieve (e.g. 'retrieveExtra') which does what you want and call it via `invokeOperation`
